### ISSUE TITLE
 Dim doesn't launch after update to newest tagged version

### ISSUE THREAD

**Issue by TheRouce** [Dusk-Labs/dim#576]
**Describe the bug**
Dim doesn't launch after update to newest tagged version

**To Reproduce**
1. pull the release from 5 months ago, create an admin account
2. pull latest release
3. check docker logs and see `thread 'main' panicked at dim-web/src/lib.rs:42:10:`  

**Expected behavior**
Dim launching without panicking

**Device and browser including versions:**
Debian 12 Kernel: 6.1.0-13-amd64

**Additional context**

I understand dim is a work in progress so I'm opening this in hopes to squash some bugs

Log output from docker:
```
2023-11-11T20:22:39.035478Z  INFO dim: Raising fd limit. limit=1048576
2023-11-11T20:22:39.035617Z  INFO nightfall::profiles: Enabling profile profile="AacTranscodeProfile"
2023-11-11T20:22:39.035722Z  INFO nightfall::profiles: Enabling profile profile="H264TranscodeProfile"
2023-11-11T20:22:39.035755Z  INFO nightfall::profiles: Enabling profile profile="H264TransmuxProfile"
2023-11-11T20:22:39.035780Z  INFO nightfall::profiles: Enabling profile profile="RawVideoTranscodeProfile"
2023-11-11T20:22:39.035805Z  INFO nightfall::profiles: Enabling profile profile="WebvttTranscodeProfile"
2023-11-11T20:22:39.035878Z  INFO nightfall::profiles: Enabling profile profile="AssExtractProfile"
2023-11-11T20:22:39.035902Z  INFO nightfall::profiles: Enabling profile profile="CudaTranscodeProfile"
2023-11-11T20:22:39.237558Z  INFO dim: Scanning for media files...
2023-11-11T20:22:39.237735Z  INFO run_scanners:get_conn_logged: dim_database: Creating new database connection
2023-11-11T20:22:39.238630Z  INFO run_scanners: dim_core::core: Starting scanner for Movies with id: 1
2023-11-11T20:22:39.240482Z  INFO run_scanners: dim_core::core: Starting scanner for Shows with id: 2
2023-11-11T20:22:39.243900Z  INFO dim: Launcing Dim
thread 'main' panicked at dim-web/src/lib.rs:42:10:
Paths must start with a `/`
stack backtrace:
2023-11-11T20:22:39.255894Z  INFO start_custom{library_id=1 media_type=Movie provider=TMDBMetadataProviderOf<K> { key: Movie }}: dim_core::scanner: Scanning library library_id=1
2023-11-11T20:22:39.259460Z  INFO start_custom{library_id=2 media_type=Tv provider=TMDBMetadataProviderOf<K> { key: Tv }}: dim_core::scanner: Scanning library library_id=2
   0:     0x562a29a725fc - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562a29a725fc - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562a29a725fc - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x562a29a725fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562a29aa365c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x562a29aa365c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x562a29a6e2fe - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x562a29a723e4 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x562a29a723e4 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x562a29a73cd3 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x562a29a739ec - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x562a29a74259 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x562a29a74157 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x562a29a72b26 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x562a29a73ea2 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x562a28c1ae73 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x562a28f6a79d - axum::routing::Router<S,B>::route::hedc6e95a71b35883
  17:     0x562a28f896cc - dim_web::library_routes::hd4c0abe1258c6a0c
  18:     0x562a28c9c981 - dim::main::{{closure}}::h13364909295088dc
  19:     0x562a28c8e5ea - tokio::runtime::park::CachedParkThread::block_on::he953b9ad2028d936
  20:     0x562a28c8ee49 - tokio::runtime::context::runtime::enter_runtime::h9e912a1bdeb42e92
  21:     0x562a28d34d6c - tokio::runtime::runtime::Runtime::block_on::hcf0f7d4701511459
  22:     0x562a28c98485 - dim::main::h04806f991137de20
  23:     0x562a28dbd6c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha19e03f98ffa2abf
  24:     0x562a28d1bf19 - std::rt::lang_start::{{closure}}::ha00da22b7db70745
  25:     0x562a29a65cbb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  26:     0x562a29a65cbb - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  27:     0x562a29a65cbb - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  28:     0x562a29a65cbb - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  29:     0x562a29a65cbb - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  30:     0x562a29a65cbb - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  31:     0x562a29a65cbb - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  32:     0x562a29a65cbb - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  33:     0x562a29a65cbb - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  34:     0x562a28ca0495 - main
  35:     0x7f7e57c70d0a - __libc_start_main
  36:     0x562a28c1b6aa - _start
  37:                0x0 - <unknown>
```

Docker compose snippet:
```

  dim:
    container_name: dim
    image: ghcr.io/dusk-labs/dim:dev
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - /var/lib/dim:/opt/dim/config
      - '/media/Movies:/Movies'
      - '/media/TV:/TV'
    devices:
      - /dev/nvidia0:/dev/nvidia0
```

**Comment by niamu** [comment]
A fix for this is in https://github.com/Dusk-Labs/dim/pull/574
